"""Prompt + tool schema for the AI onboarding config polish (#824 Phase A).

The model's ONLY job here is to choose readable resource names, groupings, and
short comments for a config that ``terrapod-query`` already discovered and
``-generate-config-out`` already generated. It returns **structured naming
decisions**, never HCL — ``onboarding_polish.apply_polish`` applies them to the
raw text deterministically. Because the model never emits an attribute value or
an import id, it cannot corrupt one; the schema below has no free-form config
field on purpose.

Output is forced through the model's native tool-calling surface (same mechanism
as the summariser), so the arguments arrive as validated JSON matching
``ONBOARDING_POLISH_JSON_SCHEMA``.
"""

from __future__ import annotations

# The tool arguments. `resources` pairs each CURRENT address with a proposed
# name (and optional group/comment). No config text is ever requested from the
# model — that is the whole safety point.
ONBOARDING_POLISH_JSON_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "resources": {
            "type": "array",
            "description": (
                "One entry per resource in the config. Omit a resource to leave its name unchanged."
            ),
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string",
                        "description": (
                            "The resource's CURRENT address exactly as it appears "
                            "in the config, in <type>.<name> form "
                            "(e.g. 'aws_eip.eipalloc_0ccdb1'). Must match a "
                            "resource in the input verbatim."
                        ),
                    },
                    "new_name": {
                        "type": "string",
                        "description": (
                            "The new LOCAL name (the part after the type). A valid "
                            "Terraform identifier: start with a letter or "
                            "underscore, then letters, digits, underscores, or "
                            "hyphens; lowercase snake_case preferred. Derive it "
                            "from the resource's Name tag or other identifying "
                            "attributes. Must be unique among resources of the "
                            "same type. The type itself never changes."
                        ),
                    },
                    "group": {
                        "type": "string",
                        "description": (
                            "Optional short section label to group related "
                            "resources under (e.g. 'Networking', 'Compute', "
                            "'IAM'). Resources sharing a group are emitted "
                            "together under a header comment. Omit for no group."
                        ),
                    },
                    "comment": {
                        "type": "string",
                        "description": (
                            "Optional one-line comment placed above the resource "
                            "to explain what it is. Keep it short; omit if it adds "
                            "nothing beyond the name."
                        ),
                    },
                },
                "required": ["address", "new_name"],
                "additionalProperties": False,
            },
        },
        "file_header": {
            "type": "string",
            "description": (
                "Optional short comment block for the top of the file (e.g. one "
                "line naming the estate being onboarded). Omit if not useful."
            ),
        },
    },
    "required": ["resources"],
    "additionalProperties": False,
}

ONBOARDING_POLISH_TOOL: dict = {
    "type": "function",
    "function": {
        "name": "submit_resource_naming",
        "description": (
            "Submit readable names, groupings, and comments for the discovered "
            "resources. You do not output configuration — only these naming "
            "decisions."
        ),
        "parameters": ONBOARDING_POLISH_JSON_SCHEMA,
    },
}


# The grounding discipline in this prompt — name/comment ONLY from what literally
# appears in the config; if it isn't there, it doesn't exist — is the same
# hard-won rule the summariser prompt lives by (rate SOLELY from PLAN_JSON, never
# invent from background context). Internally: the "just the facts" / Dragnet
# directive. Keep it prominent if this prompt is ever revised.
ONBOARDING_POLISH_SKILL_PROMPT = """\
You are a senior infrastructure engineer tidying up a Terraform/OpenTofu \
configuration that was auto-generated by importing existing, unmanaged cloud \
resources. The generator produced correct but machine-named config: every \
resource carries an opaque label derived from its cloud id (e.g. \
`aws_eip.eipalloc_0ccdb1`). You are accountable on two fronts, and a good \
tidy-up serves both:

  • Readability — an operator inheriting this config should be able to tell \
what each resource IS from its name. Opaque cloud-id labels fail that.
  • Truthfulness — a name or comment is documentation, and wrong documentation \
is worse than none. A confident, plausible-sounding name that is not backed by \
the config will mislead the operator into a bad decision. A misleading name is \
worse than an ugly one.

You will receive these inputs in the user message:
  • GENERATED_CONFIG — the resource blocks to name. This is your SOLE source of \
truth: the only facts about a resource are its type, its attributes, and its \
tags as they literally appear here.
  • PROVIDER — the provider being onboarded (e.g. `aws`). Context only.
  • CONTEXT (platform / workspace) — operator notes, when present. Background \
that may help you word a name or group — but it is NOT a licence to introduce a \
fact (an environment, an application, an owner) into a name unless that fact \
also appears in the resource's own config.

Your job is to make the config read like something a human wrote, by choosing, \
per resource:
  - a meaningful LOCAL NAME, derived from its `Name` tag or another identifying \
attribute (an EIP tagged `nat-eu-west-1a` becomes `nat_eu_west_1a`);
  - an optional GROUP label to cluster related resources (networking, compute, \
iam, …);
  - an optional one-line COMMENT where it genuinely aids understanding.

CRITICAL — every name is grounded in the config, never invented:

  Derive each name, comment, group label, and file header SOLELY from strings \
that literally appear in GENERATED_CONFIG for that resource — a `Name` tag, \
another tag value, or a concrete attribute (an attached instance / bucket / \
role, a CIDR, a port). If a fact is not in the config, it does not exist for \
you: NEVER fabricate or guess an environment (dev / staging / prod), a purpose, \
a team, an application, a region nickname, an account, or an estate/VPC name. \
The single worst failure here is a name that reads as meaningful but is made up.

  When a resource has NO `Name` tag AND no clearly-identifying attribute to name \
it from, DO NOT invent one. Return `new_name` equal to its ORIGINAL local name \
with any hyphens replaced by underscores (a valid identifier), and omit its \
comment. A tidy, honest machine name is the correct answer there — not a \
fabricated "meaningful" one. When in doubt, keep the original.

Hard rules — these define the boundary of your role:
  - You NEVER change, add, or remove any attribute value, and never touch an \
import id. You are not writing config; you only return naming decisions. The \
system applies them mechanically and copies every attribute value and import id \
verbatim — so anything you put in a `new_name`/`group`/`comment` is the ONLY \
thing you can affect.
  - Names must be valid Terraform identifiers (start with a letter or \
underscore; then letters, digits, underscores, hyphens) and UNIQUE among \
resources of the same type. Prefer lowercase snake_case. Never change a \
resource's TYPE.
  - Comments cite ONLY attributes present in that resource's own block (e.g. \
"Attached to instance i-0abc" is fine because `instance` is in the block). Omit \
the comment otherwise. Emit a `file_header` only if the config gives a real, \
factual basis for one; when in doubt, omit it.
  - Keep comments short and factual. Omit a comment, group, or rename when it \
adds nothing — a rename to the same-meaning name is noise.

Style:
  - Names and comments are operator-facing, terse, professional. No emojis, no \
first-person ("I named this…"), no marketing.

Worked example — a resource block like:
    resource "aws_eip" "eipalloc_0abc" {
      instance = "i-0abc123"
      tags = { Name = "prod-nat-1a" }
    }
  → {"address": "aws_eip.eipalloc_0abc", "new_name": "prod_nat_1a", \
"group": "Networking", "comment": "NAT EIP, attached to instance i-0abc123"} \
— every token traceable to the block. A sibling EIP with no tags and only a \
`domain = "vpc"` → {"address": "...", "new_name": "<original, hyphens→\
underscores>"} with no comment.

Call `submit_resource_naming` exactly once with one entry per resource. Return \
only the tool call — no prose, no paraphrase of the JSON in your message body."""


def render_polish_prompt(
    *,
    provider: str,
    generated_config: str,
    fleet_context: str = "",
    workspace_context: str = "",
    output_language: str = "",
) -> tuple[str, str]:
    """Render ``(system_message, user_message)`` for the polish completion.

    The system message owns the contract (the skill prompt + an optional
    output-language directive for comments). The user message carries the
    provider and the raw generated config the model reads to choose names —
    it is context only; the model returns naming decisions, not config.
    """
    parts: list[str] = [ONBOARDING_POLISH_SKILL_PROMPT]
    if output_language.strip() and output_language.strip().lower() != "english":
        parts.append(
            f"OUTPUT_LANGUAGE: Write any COMMENT text you emit in "
            f"{output_language.strip()}. Keep every identifier verbatim and "
            f"untranslated — resource names, types, tags, and group labels stay "
            f"in their original form; only free-text comments are translated."
        )
    system_message = "\n\n".join(parts)

    user_parts: list[str] = []
    if fleet_context.strip():
        user_parts.append(f"CONTEXT (platform):\n{fleet_context.strip()}")
    if workspace_context.strip():
        user_parts.append(f"CONTEXT (workspace):\n{workspace_context.strip()}")
    user_parts.append(f"PROVIDER: {provider}")
    user_parts.append(
        "GENERATED_CONFIG — the resources to name (read their tags/attributes to "
        "choose names; do not reproduce or alter this config):\n"
        f"```hcl\n{generated_config}\n```"
    )
    user_message = "\n\n".join(user_parts)
    return system_message, user_message
