"""Signed capabilities for URLs Terrapod hands to a client that sends no credential.

Four URLs are generated by us and fetched verbatim by a client that cannot carry
an `Authorization` header: the plan and apply `log-read-url`, the
configuration-version `upload-url`, and the state-version upload URL. We copied
the "no auth header" half of TFE's design without the other half — TFE's
`log-read-url` points at `archivist.terraform.io/v1/object/<signed secret>`,
where the URL *is* the credential, while ours carried a bare plan id that appears
in UI links, audit rows, Slack messages and PR comments. So anyone who learned a
run id could read its logs (GHSA-r9v9-24fv-jxm2, GHSA-63m3-56rj-qqfh).

A capability goes in the **path**, not the query string, because go-tfe's
`LogReader.read` rewrites `RawQuery` on every chunk — a `?ticket=` never
survives to the first byte. The path segment that already holds the id is reused,
so the route template is unchanged and no new route is added.

**Why the signing key is derived from the CA key.** The obvious home,
`download_tickets`, signs with `get_token_signing_key()`, which defaults to
`sha256(database_url)` — the weakness GHSA-hc47-q72v-4vcm reports, and one we
deliberately do not rotate on the release lines because rotating invalidates
every in-flight token. Signing capabilities with it would make this fix circular:
anyone who knows the DSN could mint their own. The CA private key is generated on
first startup, persisted, encrypted at rest, stable across restarts, shared
across replicas, and not derivable from the DSN — so it gives a strong
per-deployment secret with no new configuration and no migration.

**Do not "tidy" this into reusing the token signing key.** That is the
circularity this exists to avoid. Rotating the CA invalidates outstanding
capabilities, which is intended: they are short-lived.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import time

from cryptography.hazmat.primitives import serialization

#: Domain separation, so a capability for one artifact kind can never be
#: replayed as another. `verify` takes the kind it expects rather than returning
#: it, because a consumer that merely reads the kind back can forget to check it.
_HKDF_LABEL = b"terrapod/capability-url/v1"

#: The artifact kinds a capability can name. They are distinct values rather
#: than one "run" kind because the plan-log and apply-log endpoints resolve the
#: *same* run id: without separation, a capability minted for a plan log would
#: read the apply log of the same run, and a configuration-version upload
#: capability would be accepted by the state upload.
KIND_PLAN_LOG = "plan-log"
KIND_APPLY_LOG = "apply-log"
KIND_CV_UPLOAD = "cv-upload"
KIND_SV_UPLOAD = "sv-upload"

#: Long enough to outlive any plan or apply that is still streaming. TFE's
#: Archivist URLs last 25 hours; we have no run-duration cap to derive a tighter
#: bound from, and `LogReader` never re-reads the URL, so a capability that
#: expires mid-stream freezes the log with no way to renew it.
DEFAULT_TTL_SECONDS = 25 * 60 * 60


def _signing_key() -> bytes:
    """Per-deployment key derived from the CA private key. See the module docstring."""
    from terrapod.auth.ca import get_ca

    ca = get_ca()
    raw = ca.ca_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    return hashlib.blake2b(raw, person=_HKDF_LABEL[:16], digest_size=32).digest()


def _sign(payload: str) -> str:
    mac = hmac.new(_signing_key(), payload.encode("utf-8"), hashlib.sha256).digest()
    return base64.urlsafe_b64encode(mac).decode("ascii").rstrip("=")


def mint(kind: str, resource_id: str, *, ttl_seconds: int = DEFAULT_TTL_SECONDS) -> str:
    """A capability naming exactly one artifact, for a bounded window.

    The returned string goes in the path segment that would otherwise hold the
    bare id, so the route template does not change.
    """
    expires = int(time.time()) + ttl_seconds
    payload = f"{kind}:{resource_id}:{expires}"
    return f"cap-{base64.urlsafe_b64encode(payload.encode()).decode().rstrip('=')}.{_sign(payload)}"


def looks_like_capability(segment: str) -> bool:
    """Whether a path segment is a capability rather than a bare id."""
    return segment.startswith("cap-") and "." in segment


def describe_for_logging(segment: str) -> str | None:
    """The resource a capability names, for a log or audit row — never for access.

    A capability grants a read or a write, so writing one verbatim into
    `audit_logs.resource_id` would hand every auditor a live credential for the
    artifact, out of a table built to be read. Recording what it *names* instead
    is both safe and more useful than the opaque blob: an audit row that says
    `plan-log:<run id>` answers "who read this run's log", which is the question
    the table exists for.

    The payload is decoded **without** verifying the signature, because this
    answers "what did the caller ask for", which is true of a forged capability
    too — and the answer is only ever written down. `verify` is the only
    function that may decide access; this one must never be used for that, and
    returns a string that is deliberately not a bare id so it cannot be mistaken
    for one.
    """
    if not looks_like_capability(segment):
        return None
    body, _, _ = segment[len("cap-") :].partition(".")
    try:
        pad = "=" * (-len(body) % 4)
        payload = base64.urlsafe_b64decode(body + pad).decode("utf-8")
        kind, resource_id, _ = payload.split(":", 2)
    except (ValueError, UnicodeDecodeError):
        return "capability:unparseable"
    return f"{kind}:{resource_id}"


def verify(segment: str, *, expect_kind: str) -> str | None:
    """Return the resource id this capability names, or None.

    `expect_kind` is required rather than returned: both the plan-log and
    apply-log endpoints resolve the same underlying run id, so a consumer that
    read the kind back and forgot to compare it would accept a plan capability
    for an apply log.
    """
    if not looks_like_capability(segment):
        return None
    body, _, sig = segment[len("cap-") :].partition(".")
    try:
        pad = "=" * (-len(body) % 4)
        payload = base64.urlsafe_b64decode(body + pad).decode("utf-8")
        kind, resource_id, expires_s = payload.split(":", 2)
        expires = int(expires_s)
    except (ValueError, UnicodeDecodeError):
        return None
    if not hmac.compare_digest(sig, _sign(payload)):
        return None
    if kind != expect_kind:
        return None
    if time.time() > expires:
        return None
    return resource_id
