"""The signing key for stateless HMAC tokens, owned by the application.

Four stateless token families share one key — runner tokens
(`runner_tokens.py`), run-task callback tokens (`run_task_service.py`),
download tickets (`download_tickets.py`) and Slack link tokens
(`slack_link_service.py`). All four are verified purely from their
signature, so the key is the whole of their security.

**The key is generated by Terrapod and persisted in the database, exactly
as the listener CA is** (`auth/ca.py`): created on first startup inside the
lifespan, stored in a single-row table, read on every startup, with the
check-then-create serialized across replicas by a Postgres advisory lock.
That shape is not an aesthetic preference — it is what the two previous
mechanisms each got wrong:

* **Deriving it from `sha256(database_url)`** handed token forgery to
  anyone holding database credentials: a credential for another system,
  given to every client of that database, to backup and migration jobs,
  and to a DBA with no business minting platform tokens
  (GHSA-hc47-q72v-4vcm).
* **Generating it in the Helm chart** put a `randAlphaNum` in a rendered
  manifest, which is not a pure function of its inputs. Under `helm
  install` a `lookup` for the existing Secret rescued that; under `helm
  template` — which is what Argo CD and Flux run — `lookup` returns
  nothing and `.Release.IsInstall` is always true, so the generating
  branch minted a fresh key on every render: a rotation machine pointed at
  a running deployment. An application-generated key cannot have the
  problem at all, which is why the whole `lookup`/`IsInstall`/namespace-probe
  apparatus is gone rather than tightened.

A Secret injected as env has a third failure this avoids: it is snapshotted
at pod start and never refreshes, and this module used to cache it in a
process global on top of that. A rotation therefore left one replica on the
old key and one on the new, and because requests round-robin roughly half of
every run's calls returned 401 while the rest succeeded — the v1.7.3 outage.
Reading from the database on every startup means replicas cannot disagree
about a key they all load from the same row.

## Bring-your-own wins, on every startup

`token_signing_key` (Helm: `api.tokenSigningKey.existingSecret`) is
authoritative whenever it is set, and **the table is not even read**. So an
operator who supplies their own key keeps supplying it, and rotating their
own Secret takes effect on the next restart.

The alternative — adopt the operator's key into the database once and read
the database thereafter — was rejected deliberately. It makes the first
value win for ever and silently ignores every later change to an explicitly
configured setting, which is the shape of defect this project has shipped
before (a flag nothing reads). A configured key is also the one case that
needs no database at all, so a bring-your-own deployment is unaffected by
anything below.

## Adopt, do not regenerate, when upgrading onto this

`sha256(configured)` is preserved for a supplied key, and the **stored** key
for a deployment that arrives on the old fallback is `sha256(database_url)` —
the key it is already using. Both matter for the same reason: a different
key invalidates every token in flight, and those tokens are what running
plans and applies authenticate with. An apply that succeeds and then cannot
upload its state flags the workspace as diverged, so "the upgrade changed
the key" is not a cosmetic failure.

A deployment that has never executed anything has nothing in flight, so it
generates a strong key instead. Without that branch every fresh install
would start on a database-derived key, which would *regress* against the
chart-generated key of 1.7.7 onwards.
"""

import hashlib
import secrets

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from terrapod.logging_config import get_logger

logger = get_logger(__name__)

#: An operator-supplied key, via `token_signing_key`. Never stored.
PROVENANCE_CONFIG = "config"
#: 32 random bytes this deployment generated. Strong by construction.
PROVENANCE_GENERATED = "generated"
#: Adopted from the pre-2.0 `sha256(database_url)` derivation so that tokens
#: in flight across the upgrade keep verifying. Still weak, still reported.
PROVENANCE_DATABASE_URL = "database-url"

#: Stable, arbitrary key for the Postgres advisory lock that serializes signing-key
#: initialization across API replicas. Deliberately distinct from the CA's
#: (`ca._CA_INIT_ADVISORY_LOCK`, ...122): sharing one would make two unrelated
#: initializations contend, and a future change to either would silently couple them.
_INIT_ADVISORY_LOCK = 776699001123

_signing_key: bytes | None = None
_provenance: str | None = None

#: Set once a problem has been reported, so something true for the life of the
#: process is not logged again on every token mint.
_reported: bool = False


def describe_live_key_problem(*, configured: str, provenance: str) -> str | None:
    """Return the problem with the key that is actually live, or None.

    Pure: no logging, no raising, no globals. The caller decides what to do
    with the answer, which is what makes this directly testable.

    **The weakness of an adopted key is reported on provenance, never on
    score.** The shipped default DSN measures as strong (see
    `terrapod/secret_strength.py`) — it is weak because the database URL is
    shared with everything that talks to the database, not because it is
    guessable. A strength estimator cannot see that, so it must not be asked.
    """
    from terrapod.secret_strength import describe_weakness

    if provenance == PROVENANCE_GENERATED:
        return None
    if provenance == PROVENANCE_CONFIG:
        return describe_weakness(configured, name="token_signing_key")
    if provenance == PROVENANCE_DATABASE_URL:
        return (
            "the token signing key was adopted from this deployment's database URL, "
            "so anyone who learns that URL can mint runner tokens, run-task callback "
            "tokens, download tickets and Slack link tokens. It was adopted rather "
            "than replaced so that tokens in flight across the upgrade kept working. "
            "Replace it: set token_signing_key (Helm: api.tokenSigningKey) to a "
            "generated secret — openssl rand -base64 32 — which takes effect on the "
            "next restart and invalidates tokens minted under the old key"
        )
    # A provenance this build does not know means the row was written by a newer
    # version. Refusing is the only safe answer: the alternative is treating an
    # unknown key as trustworthy.
    return f"unrecognised token signing key provenance {provenance!r}"


def _report(problem: str | None, *, strict: bool) -> str | None:
    """Log the problem once, or raise it under `strict`."""
    global _reported  # noqa: PLW0603
    if problem is None:
        return None
    if strict:
        raise ValueError(problem)
    if not _reported:
        _reported = True
        logger.warning("weak token signing key", problem=problem)
    return problem


async def init_token_signing_key(db: AsyncSession) -> bytes:
    """Resolve the signing key for this process and cache it.

    Called from the app lifespan, before anything can mint a token.

    1. A configured key wins and the table is not read (see the module
       docstring — bring-your-own stays authoritative).
    2. Otherwise take the advisory lock and load the newest stored key.
    3. If there is none, adopt the database-URL derivation when this
       deployment has executed runs, and generate 32 random bytes when it
       has not.
    """
    global _signing_key, _provenance  # noqa: PLW0603

    from terrapod.config import settings
    from terrapod.db.models import TokenSigningKey

    strict = bool(settings.require_strong_secrets)

    configured = (settings.token_signing_key or "").strip()
    if configured:
        # `sha256(configured)`, not the raw bytes: every deployment that already
        # supplies a key is using the hash, and handing those deployments a
        # different key would invalidate their in-flight tokens.
        key = hashlib.sha256(configured.encode()).digest()
        # Report BEFORE publishing the key, so that a strict-mode refusal leaves
        # nothing initialized and `get_token_signing_key()` keeps raising. The
        # app lifespan lets this propagate and the pod dies either way, but the
        # CA beside it IS wrapped in a try/except that warns and continues — so a
        # future caller copying that shape must not end up running happily on a
        # key this function refused.
        _report(
            describe_live_key_problem(configured=configured, provenance=PROVENANCE_CONFIG),
            strict=strict,
        )
        _signing_key = key
        _provenance = PROVENANCE_CONFIG
        logger.info("Token signing key taken from configuration", provenance=_provenance)
        return _signing_key

    # Serialize check-then-create across replicas with a transaction-scoped
    # advisory lock, for the same reason `init_ca` does (#1060): two replicas
    # starting against a database with no key would each generate one and each
    # insert a row, leaving the replicas signing with *different* keys and
    # rejecting each other's tokens — which is the v1.7.3 outage reproduced by a
    # different route. The lock makes concurrent starters queue: the first
    # creates the key, the rest load it. It releases when this transaction
    # commits below.
    await db.execute(text("SELECT pg_advisory_xact_lock(:k)"), {"k": _INIT_ADVISORY_LOCK})

    result = await db.execute(
        select(TokenSigningKey).order_by(TokenSigningKey.created_at.desc()).limit(1)
    )
    row = result.scalar_one_or_none()

    if row is not None:
        key = _decode_stored_key(row.key)
        provenance = row.provenance
        # Release the lock held on this transaction; nothing was written.
        await db.commit()
        logger.info("Loaded token signing key from database", provenance=provenance)
    else:
        if await _has_executed_runs(db):
            key = hashlib.sha256(str(settings.database_url).encode()).digest()
            provenance = PROVENANCE_DATABASE_URL
        else:
            key = secrets.token_bytes(32)
            provenance = PROVENANCE_GENERATED
        db.add(TokenSigningKey(key=key.hex(), provenance=provenance))
        await db.commit()
        logger.info("Stored a new token signing key", provenance=provenance)

    # Reported before publishing, for the reason given on the configured path.
    _report(
        describe_live_key_problem(configured="", provenance=provenance),
        strict=strict,
    )
    _signing_key = key
    _provenance = provenance
    return key


def _decode_stored_key(stored: str) -> bytes:
    """Decode a stored hex key, refusing anything that is not 32 bytes.

    A stored value that will not decode means the row is unusable — most
    likely the encryption key changed, so `EncryptedText` handed back
    something that is not what was written. Refusing is correct: signing with
    a mangled key would reject every token minted before the restart while
    looking healthy.
    """
    try:
        key = bytes.fromhex(stored.strip())
    except ValueError as exc:
        raise RuntimeError(
            "stored token signing key is not valid hex; if encryption at rest was "
            "enabled or its key changed, the stored value cannot be decrypted"
        ) from exc
    if len(key) != 32:
        raise RuntimeError(f"stored token signing key is {len(key)} bytes, expected 32")
    return key


async def _has_executed_runs(db: AsyncSession) -> bool:
    """Has this deployment ever executed a run?

    The question behind it is "could a token minted under the old derivation
    still be in flight", and a deployment with no runs has never minted a
    runner token, a callback token or a download ticket. It is deliberately
    conservative in the safe direction: anything that has been used adopts,
    which cannot break a live run, and the cost is a weak-but-reported key
    the operator replaces.
    """
    from terrapod.db.models import Run

    result = await db.execute(select(Run.id).limit(1))
    return result.scalar_one_or_none() is not None


def get_token_signing_key() -> bytes:
    """Return the process-wide 32-byte HMAC signing key.

    Raises when the key has not been initialized, the way `get_ca()` does.
    There is deliberately no lazy fallback: the only value available without
    the database is the database-URL derivation this change exists to remove,
    so silently minting tokens with it would reintroduce the vulnerability at
    exactly the moment something went wrong.
    """
    if _signing_key is None:
        raise RuntimeError(
            "token signing key not initialized — call init_token_signing_key() first"
        )
    return _signing_key


def get_provenance() -> str | None:
    """Where the live key came from, or None before initialization.

    Public because the branch taken IS the behaviour — which of the two sources
    is live, and whether a used deployment adopted rather than regenerated — and
    the tests assert it through here rather than reaching into a global. No
    operator-facing surface reads it yet: startup logs the provenance and warns
    when it is weak, which is where an operator looks, and a preflight check
    would run before the migration that creates the table. It is the hook if a
    diagnostic ever wants one.
    """
    return _provenance


def _reset_cache_for_tests() -> None:
    """Clear the cached key (tests that mutate config only)."""
    global _signing_key, _provenance, _reported  # noqa: PLW0603
    _signing_key = None
    _provenance = None
    _reported = False


def _set_key_for_tests(key: bytes, provenance: str = PROVENANCE_GENERATED) -> None:
    """Install a key without a database, for tests that only need to sign."""
    global _signing_key, _provenance  # noqa: PLW0603
    _signing_key = key
    _provenance = provenance
