#!/usr/bin/env python3
"""Regenerate the committed Python dependency locks (GHSA-rgvw-c74c-h75w).

Run this through ``scripts/lock-python-deps.sh``, which executes it inside the
same base image and the same Poetry version the images build with. Running it
against a different Poetry writes a lock format the image build cannot read
(Poetry 2.x writes lock-version 2.1; the builds use Poetry 1.8.4, which refuses
it), so the wrapper exists to stop that happening by accident.

What it produces, all committed:

``services/poetry.lock``
    Poetry's own lock for the main project. The api image exports its ``main``
    group from this at build time and installs with ``--require-hashes``; the
    test image installs from it directly; the Python Audit job audits the
    export of it. One reviewed resolution, three consumers.

``services/requirements-{listener,migrations,runner}.txt``
    Fully pinned, fully hashed requirement sets for the three minimal images.
    Those images have no Poetry in them — they are ``pip install`` images — so
    the lock artifact for each is the exported requirements file itself, and it
    is what the image installs with ``--require-hashes``.

Each minimal set is resolved on its own, because each is its own installable
manifest with its own floors — and those floors genuinely differ, so the sets
can legitimately land on different versions of a shared package. They mostly do
not, but the migrations image floats botocore free of the ``aiobotocore`` pin the
main project inherits, so this is not a property to assert. What IS asserted, in
``services/tests/test_dependency_pins.py``, is that every line here is pinned and
hashed and that each manifest's floors are satisfied by what was pinned for it.
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys
import tempfile
import tomllib

from packaging.requirements import Requirement

REPO = pathlib.Path(__file__).resolve().parents[1]
SERVICES = REPO / "services"

# Minimal dependency set -> (its manifest, the requirements file it produces).
# Keep in step with the three ``COPY services/pyproject-<name>.toml`` lines in
# docker/Dockerfile.{listener,migrations,runner}.
MINIMAL_SETS = ("listener", "migrations", "runner")

HEADER = """\
# This file is GENERATED. Do not edit it by hand.
#
# Regenerate with:  scripts/lock-python-deps.sh
# Source manifest:  services/pyproject-{name}.toml
#
# Every line is pinned with == and carries every published hash for that
# version, so docker/Dockerfile.{name} installs it with --require-hashes: the
# bytes that reach the image are the bytes reviewed here, on both arches, and a
# malicious upstream release cannot land in a signed image without this file
# changing first (GHSA-rgvw-c74c-h75w).
"""


def run(cmd: list[str], cwd: pathlib.Path) -> None:
    print(f"+ {' '.join(cmd)}  (in {cwd})", flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)


def poetry_dependency(raw: str) -> tuple[str, object]:
    """Translate one PEP 508 requirement into a Poetry dependency entry."""
    req = Requirement(raw)
    if req.marker is not None:
        # Dropping a marker silently would change what the image installs.
        raise SystemExit(
            f"{raw!r} carries an environment marker, which this script does not "
            "translate. Add marker support here rather than losing the constraint."
        )
    spec = str(req.specifier) or "*"
    if req.extras:
        return req.name, {"version": spec, "extras": sorted(req.extras)}
    return req.name, spec


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_poetry_pyproject(manifest: pathlib.Path) -> str:
    """Build a ``[tool.poetry]`` pyproject from a PEP 621 ``[project]`` one.

    Poetry 1.8.4 does not read ``[project]`` dependencies, and the three
    minimal manifests are PEP 621 because they are installed with plain pip.
    Rather than convert them (and change what those images install), translate
    a throwaway copy here purely so Poetry can resolve and hash the same set.
    """
    data = tomllib.loads(manifest.read_text())
    project = data["project"]

    lines = [
        "[tool.poetry]",
        f"name = {quote(project['name'])}",
        f"version = {quote(project['version'])}",
        'description = "generated by scripts/lock-python-deps.py"',
        'authors = ["Terrapod"]',
        "package-mode = false",
        "",
        "[tool.poetry.dependencies]",
        f"python = {quote(project['requires-python'])}",
    ]
    for raw in project["dependencies"]:
        name, entry = poetry_dependency(raw)
        if isinstance(entry, str):
            lines.append(f"{name} = {quote(entry)}")
        else:
            extras = ", ".join(quote(e) for e in entry["extras"])
            lines.append(f"{name} = {{version = {quote(entry['version'])}, extras = [{extras}]}}")
    lines += ["", "[build-system]", 'requires = ["poetry-core"]']
    lines.append('build-backend = "poetry.core.masonry.api"')
    return "\n".join(lines) + "\n"


def lock_main() -> None:
    print("── services/poetry.lock (main project)", flush=True)
    run(["poetry", "lock", "--no-interaction", "--no-ansi"], cwd=SERVICES)


def lock_minimal(name: str) -> None:
    manifest = SERVICES / f"pyproject-{name}.toml"
    out = SERVICES / f"requirements-{name}.txt"
    print(f"── {out.relative_to(REPO)} (from {manifest.name})", flush=True)

    with tempfile.TemporaryDirectory() as tmp:
        work = pathlib.Path(tmp)
        (work / "pyproject.toml").write_text(render_poetry_pyproject(manifest))
        run(["poetry", "lock", "--no-interaction", "--no-ansi"], cwd=work)
        run(
            [
                "poetry",
                "export",
                "--only",
                "main",
                "--format",
                "requirements.txt",
                "--output",
                "requirements.txt",
                "--no-interaction",
                "--no-ansi",
            ],
            cwd=work,
        )
        body = (work / "requirements.txt").read_text()

    out.write_text(HEADER.format(name=name) + body)


def main() -> int:
    if shutil.which("poetry") is None:
        print("poetry is not on PATH — run scripts/lock-python-deps.sh", file=sys.stderr)
        return 1
    lock_main()
    for name in MINIMAL_SETS:
        lock_minimal(name)
    print("\nDone. Review the diff, then commit the lock and the requirements files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
