#!/usr/bin/env bash
# Regenerate the committed Python dependency locks (GHSA-rgvw-c74c-h75w).
#
#   scripts/lock-python-deps.sh
#
# Writes services/poetry.lock and services/requirements-{listener,migrations,
# runner}.txt. Review the diff and commit them: that review IS the control. A
# dependency change is now a lock update, deliberately — the images install
# exactly what is written down here and nothing else.
#
# It runs inside the same base image and the SAME Poetry version the images
# build with, because the lock format is version-specific: Poetry 2.x writes
# lock-version 2.1, and the Poetry 1.8.4 in the Dockerfiles refuses to read it.
# A lock generated by whatever Poetry happens to be on the host therefore fails
# every image build, so the container is not a convenience — it is the point.

set -euo pipefail
source "$(dirname "$0")/lib.sh"

# Keep in step with the `poetry==` pins in docker/Dockerfile.api and
# docker/Dockerfile.test, and with BASE_IMAGE in all of docker/Dockerfile.*.
POETRY_VERSION="${POETRY_VERSION:-1.8.4}"
BASE_IMAGE="${BASE_IMAGE:-python:3.14-slim}"

info "Regenerating Python locks with Poetry ${POETRY_VERSION} in ${BASE_IMAGE}..."

# No --platform. Poetry resolves for every environment the `python` constraint
# admits and records every published file hash per package, so the lock and the
# exports are not architecture-specific — which is exactly what lets one lock
# serve both the amd64 and arm64 image builds. Pinning the platform here would
# only force a second base-image pull on an arm64 host for no gain.
docker run --rm \
  -v "${REPO_ROOT}:/repo" \
  -w /repo \
  "${BASE_IMAGE}" \
  sh -c "pip install --no-cache-dir --quiet 'poetry==${POETRY_VERSION}' packaging \
         && python3 /repo/scripts/lock-python-deps.py"

success "Locks regenerated. Review the diff before committing."
